# Site settings
name: YG的技术BLOG
email: yang@clewyo.cc
author: Yang Guang
url: https://github.com/CNS1mple/CNS1mple.github.io
resume_site: https://github.com/CNS1mple
github: https://github.com/CNS1mple/
baseurl: ""
description: 千里之行，始于足下。
meta_description: YG的技术BLOG 杨光 算法 蓝桥杯 PAT
motto: Stay determined.
banner: 千里之行，始于足下。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: CNS1mple

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

